---
- name: Provision an EC2 Instance
  hosts: local
  connection: local
  gather_facts: False
  tags: provisioning
    # Necessary Variables for creating/provisioning the EC2 Instance
  vars:
    instance_type: t2.micro
    security_groups: ['CD-Liferay-SG', 'CD-SG'] # Change the security group name here
    image: ami-1780a878 # This is an AMI i created myself
    keypair: CD-Demo # This is one of my keys that i already have in AWS
    region: ap-south-1 # Change the Region
    count: 1
    EIP: 13.233.211.43

    # Task that will be used to Launch/Create an EC2 Instance
  tasks:
    - name: Launch the new EC2 Instance
      local_action: ec2 
                    group={{ security_groups }} 
                    instance_type={{ instance_type}} 
                    image={{ image }} 
                    wait=true 
                    region={{ region }} 
                    keypair={{ keypair }}
                    count={{count}}
      register: ec2
     
#- name: Debug ec2_info
#  debug: var=ec2

- name: associate an elastic IP with an instance
  ec2_eip: instance_id={{ item.id }} ip={{ EIP }} region={{ region }} 
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  local_action: wait_for
                host={{ EIP }}
                port=22
                state=started

- name: Add tag to Instance(s)
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: "{{ ec2.instances }}"
  args:
  tags:
    Name: webserver

