- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/
- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg
- name: Install Firewalld
  yum: name=firewalld state=absent
- name: Firewalld service state
  service: name=firewalld state=stopped enabled=no
- name: Turn Off SELinux
  command: setenforce 0
